services:
  db:
    image: mysql:8.0
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: postgres
      MYSQL_DATABASE: multiagent_ppt
    command: --default-authentication-plugin=mysql_native_password

  app:
    build: .
    container_name: nextjs_app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:postgres@db:3306/multiagent_ppt
      A2A_AGENT_OUTLINE_URL: http://127.0.0.1:10001
      A2A_AGENT_SLIDES_URL: http://127.0.0.1:10012
    command: ["pnpm", "start"]  # 如果你用于本地开发
    # command: ["pnpm", "start"] # 如果你 build 之后运行

volumes:
  mysql_data:
