"""Prompt templates module"""

from .planning_prompts import SPLIT_TOPIC_AGENT_PROMPT, OUTLINE_GENERATION_PROMPT
from .research_prompts import RESEARCH_TOPIC_AGENT_PROMPT, DOCUMENT_ANALYSIS_PROMPT
from .generation_prompts import XML_PPT_AGENT_NEXT_PAGE_PROMPT, CHECKER_AGENT_PROMPT

__all__ = [
    "SPLIT_TOPIC_AGENT_PROMPT",
    "OUTLINE_GENERATION_PROMPT",
    "RESEARCH_TOPIC_AGENT_PROMPT",
    "DOCUMENT_ANALYSIS_PROMPT",
    "XML_PPT_AGENT_NEXT_PAGE_PROMPT",
    "CHECKER_AGENT_PROMPT",
]
